services:
  - type: web
    name: digital-rights-tool-backend
    env: node
    rootDir: backend
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: digital-rights-tool-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
    healthCheckPath: /health

databases:
  - name: digital-rights-tool-db
    databaseName: digital_rights_tool
    user: digital_rights_tool_user
    plan: free
